[window]
padding = { x = 10, y = 10 }
decorations = "full" # or "none" for a borderless look
opacity = 0.95

[font]
size = 8

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[colors.primary]
background = "#05080d"
foreground = "#aacfd1"

[colors.normal]
black   = "#aacfd1"
red     = "#aacfd1"
green   = "#aacfd1"
yellow  = "#aacfd1"
blue    = "#aacfd1"
magenta = "#aacfd1"
cyan    = "#aacfd1"
white   = "#aacfd1"

